Initial widget development
shortlist-digital/agreable-image-led-feature-widget-plugin pull request #1
Opened 2017-08-03 11:18 UTC by leonoragilmour

Corresponding documentation https://github.com/shortlist-digital/documents/tree/master/technical-architecture/content-widgets/image-led-feature

2017-08-03 11:28 UTC, thomasdigby commented on widget-loader-acf.php
> +$widget_config["content-sizes"] = array('main'); // main, main-full-bleed, sidebar
Is this comment still relevant? /shrug

2017-08-03 11:28 UTC, thomasdigby commented on widget-loader-acf.php
> +$widget_config["content-sizes"] = array('main'); // main, main-full-bleed, sidebar
Ah sorry, is this related to the CMS?

2017-08-03 11:30 UTC, leonoragilmour commented on widget-loader-acf.php
> +$widget_config["content-sizes"] = array('main'); // main, main-full-bleed, sidebar
this is cms but I must confess I have never taken the time to know what main / main full bleed / sidebar even means 😳

2017-08-03 11:48 UTC, leonoragilmour commented
![](https://github.trello.services/images/mini-trello-icon.png) [WIDGET: Image Led Feature](https://trello.com/c/EFgR8w7u/153-widget-image-led-feature)

2017-08-07 15:56 UTC, ecoad commented on widget-loader-acf.php
> +$widget_config["content-sizes"] = array('main'); // main, main-full-bleed, sidebar
It's a feature which we don't currently make use of.

2017-08-07 16:07 UTC, ecoad commented
Sorry, can you take a look at this first: https://github.com/shortlist-digital/documents/pull/49

2017-08-08 11:35 UTC, leonoragilmour commented
@ecoad Have done :)

2017-08-08 14:37 UTC, ecoad requested changes
Request changes to have multiple posts and multiple lists

2017-08-08 14:37 UTC, ecoad commented on widget-loader-acf.php
> +      'key' => $key . '_post',
`$key . '_posts',`

2017-08-08 14:37 UTC, ecoad commented on widget-loader-acf.php
> +      'name' => 'post',
'posts',

2017-08-08 14:37 UTC, ecoad commented on widget-loader-acf.php
> +      'label' => 'Choose a post to feature',
"Manually add posts to widget"

2017-08-08 14:37 UTC, ecoad commented on widget-loader-acf.php
> +      'ui' => 1,
Missing:

```
      'multiple' => 1,
```

2017-08-08 14:37 UTC, ecoad commented on widget-loader-acf.php
> +      'ui' => 1,
Missing:

```
      'multiple' => 1,
```

2017-08-08 15:56 UTC, leonoragilmour commented on widget-loader-acf.php
> +      'ui' => 1,
Oh! Is this feature like a carousel then?

2017-08-10 15:09 UTC, leonoragilmour commented
I _think_ this is good to go now... I've said that a few times though, so ... 😅

2017-08-15 13:59 UTC, ecoad approved these changes

2017-08-15 13:59 UTC, merged

2017-08-15 14:01 UTC, ecoad commented
Tagged with v1.0.0